### ISSUE TITLE
SFTP connection issue

### ISSUE THREAD

**Issue by Flayks** [FileShuttle/fileshuttle#10]
Hello there,
I tested Fileshuttle on Mavericks (10.9.1) and I have a issue to connect with my SFTP account (port 22). I have absolutely no log on the server neither on my Mac.
I also tested the github repo code with XCode but same problem.
Do you have an idea why?

**Comment by julienma** [comment]
hey, weighing in on that topic, it's far easier to set up a proper SFTP server than SCP.
Unfortunately I don't have any knowledge in osx app, but let me know how I can help implementing real SFTP.
Would anyone like to work on that, Cc @anthonysomerset?

**Comment by julienma** [comment]
I quickly had a look at source, and as said, I know nothing about obj-c.
However I found this in https://github.com/FileShuttle/fileshuttle/blob/master/MVSFTPFileUpload.m#L185

```
scpBinary = @"/usr/bin/scp";
```

As scp and sftp both have the same syntax for uploading files, do you think SFTP would work if we changed it with:

```
scpBinary = @"/usr/bin/sftp";
```

?

**Comment by julienma** [comment]
Bah, forget my previous comment, sftp **cannot** upload without logging into some kind of interactive shell.

**Comment by anthonysomerset** [comment]
closing this in favour of resolving #18 

Going to Move current SFTP logic to SCP and create a new proper SFTP logic based on an SSH2 lib (probably NMSSH - although i haven't ruled out the Idea of using ConnectionKit as would also kill the AWS S3 stone in #13 

all this is going in to the v3.x branch at this time - i have yet to release a dev build at this time
