### ISSUE TITLE
Support SSH keys

### ISSUE THREAD

**Issue by dewey** [FileShuttle/fileshuttle#14]
Hi,

not sure if this is still under active development but it's exactly the app I'm looking for so I'd like to know if you thought about adding support for ssh keys instead of passwords. I only use key based logins on my servers and other sftp clients (Panic's Transmit is one example) are just picking it up from the default location `~/.ssh/` but that's not working if I just leave the password field empty.

I'd also be great for these kind of issues to have some kind of "Check connection" button in the preferences window, is there a better way to debug why it's not uploading? There's nothing in my system log or the `auth.log` on the server.

Thanks!

**Comment by jgillman** [comment]
:+1: I'm in exactly the same situation. Would be nice to have key support or at least a "Check connection" or log file so I can get some feedback on why it's not working.

**Comment by funkenstrahlen** [comment]
Would like to see support for this feature too :smiley:

**Comment by anthonysomerset** [comment]
going to be fixed as part of #18 - proper SSH2 based SFTP support rather than just SCP
