### ISSUE TITLE
Authentication not working.

### ISSUE THREAD

**Issue by nelder** [FileShuttle/fileshuttle#26]
A server I can connect to and upload to using terminal's SFTP command is showing a red do not enter sign over the icon when I try to upload a screenshot with the program. I have tried the build promoted on the website as well as the newer development build here on github. Any thoughts?

**Comment by frdmn** [comment]
Did you peek into `/var/log/auth.log`? Anything helpful in there?

**Comment by nelder** [comment]
pam_env(sshd:session): Unable to open env file: /etc/default/locale: No such file or directory

**Comment by anthonysomerset** [comment]
does - your server support SCP? SFTP currently is the incorrect name as its actually just doing SCP which is a slightly different protocol and i know it doesn't work in some cases - most notably CloudLinux Servers with CageFS enabled

**Comment by nelder** [comment]
Oh I had created an account with sftp privileges only, I will need to allow that for the account then.

**Comment by nelder** [comment]
So it seems the easy way to set up a restricted account like this (http://passingcuriosity.com/2014/openssh-restrict-to-sftp-chroot/) does not allow scp protocol. Any chance of support for sftp protocol and scp protocol separately? The dropdown showing ftp and sftp is a bit misleading if sftp really is using scp. Or perhaps I will explore http://pizzashack.org/rssh/ to create an account with scp access to its directory.

**Comment by nelder** [comment]
Seems as though getting SCP working in a limited manner is more difficult than getting SFTP working in a limited capacity. Would it be possible to have a selection between FTP SCP and SFTP within the app?

**Comment by anthonysomerset** [comment]
yes this is underway - i'm going to close this and direct further comments to #18
