### ISSUE TITLE
Custom short URL

### ISSUE THREAD

**Issue by BigJazzz** [FileShuttle/fileshuttle#29]
Hi all

Any chance of having an option to use the file URI straight up? My domain is already short, and I upload the files with a random hash filename. Having _that_ copy straight to my clipboard, as opposed to the sht.tl URI, would be handy, especially if sht.tl happens to be unreachable for some reason.

**Comment by BigJazzz** [comment]
This was previously mentioned (in a slightly different fashion) here: [https://github.com/michaelvillar/fileshuttle/issues/1](https://github.com/michaelvillar/fileshuttle/issues/1)

**Comment by anthonysomerset** [comment]
yeah you just disable the url shorterner entirely and put your short url path in the URL field

**Comment by BigJazzz** [comment]
Ah, of course. Thank you. I seem to have missed that option.
