### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by luco** [FileShuttle/fileshuttle#33]

**Comment by SnakeO** [comment]
I think so?

**Comment by rafaelderolez** [comment]
_Latest commit [7586690](https://github.com/FileShuttle/fileshuttle/commit/75866904a4776d5d28f5562b84fa1562da1ff0b1) on 13 Oct 2015._
 
I'd say it isn't.

**Comment by anthonysomerset** [comment]
No it isn't really - i've moved away from Mac as my daily driver so haven't used the app myself for sometime - if anyone wants to take it over then i will gladly give write access to the repo accordingly

**Comment by jariz** [comment]
Hi! I've taken over development, it'll be a while (at least a few months) before it gets an update gets released again, but if you're interested, you can view my current plans here:
https://www.notion.so/Fileshuttle-4-1a4d3226f73940b689e774bec120e072
