### ISSUE TITLE
appcast issues

### ISSUE THREAD

**Issue by core-code** [FileShuttle/fileshuttle#34]
appcast https://fileshuttle.io/update.xml lists the newest release as

http:/fileshuttle.io/fileshuttle-2.1.zip

this is not a URL. there is one slash missing

**Comment by anthonysomerset** [comment]
this was a super easy fix - now done

**Comment by core-code** [comment]
thanks!

**Comment by jariz** [comment]
I'm propagating the DNS back to GH pages now, didn't know the site was hosted on there. Should be live soon.
