### ISSUE TITLE
Domain offline :(

### ISSUE THREAD

**Issue by jariz** [FileShuttle/fileshuttle#35]
Any chance we can get it back up? Been a faithful user of this tool for years now, and it's still functioning just fine, but can't share this tool with my friends anymore. :(

**Comment by jariz** [comment]
I'd be willing to host it myself btw.

**Comment by frdmn** [comment]
The domain is not registered at the very moment. You can go and grab it at the domain registry of your choice if you like.

**Comment by jariz** [comment]
Thanks for the headsup, should be online now.

**Comment by anthonysomerset** [comment]
Hi All

this project needs a new maintainer - i've moved away from Mac as my "daily driver" so haven't used the app for some time

**Comment by jariz** [comment]
Hi @anthonysomerset, I'd be interested in picking this up.
I've made a couple apps in the past: [Noti](https://noti.center) and [Akku](https://akku.software).
I'll have to rewrite it in Swift because I don't understand ObjC all that much, but that's probably only good for the project in the long run :)

**Comment by anthonysomerset** [comment]
agreed - it was one of the many things on my radar from long back including improved SFTP support and other cloud services - sent you an invite to the org now
